### ISSUE TITLE
Express, Fastify, Hapi Koa, Raw node and Restify May 2018 benchmark update

### ISSUE THREAD

**Issue by Extarys** [PlainSight/NodeRestPerfTest3#5]
I wanted an up to date benchmark so I thought I'd post it here.
Made on a Ryzen 1800X @ 4.00 GHz with 32 Gb of RAM.

`ab -k -n 50000 -c 100 -t 20 http://127.0.0.1:8095`

![node benchmark - req sec](https://user-images.githubusercontent.com/11581433/39569843-6883e28c-4e94-11e8-8e2e-38f6aac4b9fc.png)

![node benchmark - details](https://user-images.githubusercontent.com/11581433/39569842-68736a10-4e94-11e8-915a-f4ccdeee59ab.png)

**Comment by amitguptagwl** [comment]
This repo is not in active phrase from a long time. Hence I've mentioned your comparison result [here](https://github.com/amitguptagwl/NodeRestPerfTest3/blob/master/Result.md)

**Comment by Extarys** [comment]
Awesome, thanks! I had no idea where to post this. :smile: 

EDIT: node version 9.11.1, npm version 6.0
