### ISSUE TITLE
Compare another framework with HyronJS

### ISSUE THREAD

**Issue by thangdjw** [PlainSight/NodeRestPerfTest3#7]
Hi, I recently developed a new framework, called [Hyron](https://www.npmjs.com/package/hyron), which I hope will soon become a popular framework, replacing the existing frameworks like express, hapi, koa ...
Now, I want to compare the performance of my framework with other frameworks. Hope to be of help to you.
We hope you join us in building and developing the project is becoming stronger

Any feedback, please send to the mailbox : thangphung.work@gmail.com

**Comment by amitguptagwl** [comment]
This repo is no more active. So you may raise a PR on https://github.com/amitguptagwl/NodeRestPerfTest3
